language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
dist: bionic
services:
  - xvfb
before_install:
  - sudo apt-get -y install libglfw3-dev
install:
  - pip install -e.
script:
  - pytest
